### ISSUE TITLE
Mesh alignement

### ISSUE THREAD

**Issue by raphael2692** [VincentStimper/icp#1]
Hello @VincentStimper , thank you for your repository. I would like to understand how to use your code to align one mesh to another. 

I tried loading the mesh and turning the vertex coordinates into arrays via a python package named pyVista. Then I tried to feed them to your algorithm. This is how i call the algorithm:

```python
import pyvista as pv

template_mesh = pv.PolyData("template_norm.obj") # reference mesh
scene_mesh = pv.PolyData("scene_norm.obj") # mesh to be aligned (different scale and origin)

scale, offset = icp(np.array(scene_mesh.points, dtype="float64"), np.array(template_mesh.points, dtype="float64"), dim_offset="all", dim_scale="all", num_iter=50, use_gpu=False)
```

results:
```bash
Scale: [nan nan nan]
Offset: [nan nan nan]
```

**Comment by VincentStimper** [comment]
Hello @raphael2692 
without having access to the data it is hard to judge what the reason for the nans is. If you are dealing with a mesh, your might have to reshape the data such that the first dimension represents the number of datapoints and the second the features, e.g. x, y, and z coordinates. So your arrays must have the shape N x 3.
You should also check whether the example notebook is working in your environment to make sure it is not a dependency issue.

**Comment by raphael2692** [comment]
The example runs fine. The input shape is the following:

```python
template_mesh = pv.PolyData("template_norm.obj")
print(template_mesh.points.shape)
print(template_mesh.points)

>>>(28672, 3)
>>>pyvista_ndarray([[ 435.51758,   68.87077,  492.01025],
                 [ 453.29355,   75.78145,  492.64285],
                 [ 449.05862,   71.8935 ,  490.66092],
                 ...,
                 [ 601.823  , 1450.805  ,  335.7489 ],
                 [ 557.8587 , 1453.4105 ,  323.3078 ],
                 [1094.9977 , 1333.2723 ,  105.14885]], dtype=float32)
```

The same goes for the other input, _scene_norm.obj_.

**Comment by VincentStimper** [comment]
I think the problem is that your dataset is pretty large. In ICP, distances between every pair of points need to be computed, i.e. you end up with tensors with O(N ^ 2) elements. For your case, this is larger than 2 ^ 31 and hence might lead to overflow issues when indexing those tensors. I had this problem before, and, unfortunately, it seems to be a problem inherent to the framework, so there is nothing I can do to fix it for this package.
But what you can do is to just subsample your arrays, e.g. only take every 10th. This should be sufficient to align the datasets and will be faster to run as well.

**Comment by raphael2692** [comment]
Just in case you want to know, I sampled down the mesh using poisson-disk down to 1000 vertices but i still got the nans. I managed to get a result normalizing the input arrays via sklearn, although I am not sure how to interpret the results (the real scale difference is 4 times up from scene to template). 

```python 
>>>Scale: [0.99877591 0.99877591 0.99877591]
>>>Offset: [0.00057436 0.00074789 0.00100556]
```

**Comment by VincentStimper** [comment]
I see, so maybe you the high variance in your data caused numerical instabilities. Thank you, I might incorporate the normalization in a future version of the package.
If you normalize both datasets independently, the scale difference might disappear automatically. You have to scale both datasets with the same mean and standard deviation.
